index:
    path:     /
    defaults: { _controller: RottenwoodArticleBundle:Default:index }

# Страница со статьей
article_show:
    pattern:  /article/{articleId}
    defaults: { _controller: RottenwoodArticleBundle:Default:article }
