index:
    path:     /
    defaults: { _controller: RottenwoodArticleBundle:Default:index }

# Страница со статьей
article_show:
    pattern:  /article/{articleId}
    defaults: { _controller: RottenwoodArticleBundle:Default:article }

# Отображение статьи при ajax-запросе
article_show_text:
    pattern:  /article/{articleId}/text
    defaults: { _controller: RottenwoodArticleBundle:Default:articleText }

# API
api_get_articles_by_author:
    pattern:  /api/getarticles
    defaults: { _controller: RottenwoodArticleBundle:Api:getArticles }

api_add_article:
    pattern:  /api/addarticle
    defaults: { _controller: RottenwoodArticleBundle:Api:addArticle }

api_delete_article:
    pattern:  /api/deletearticle
    defaults: { _controller: RottenwoodArticleBundle:Api:deleteArticle }

api_get_one_article:
    pattern:  /api/getonearticle
    defaults: { _controller: RottenwoodArticleBundle:Api:getOneArticle }

api_edit_article:
    pattern:  /api/edit
    defaults: { _controller: RottenwoodArticleBundle:Api:editArticle }

api_search_article:
    pattern:  /api/search
    defaults: { _controller: RottenwoodArticleBundle:Api:search }

api_get_authors:
    pattern:  /api/getauthors
    defaults: { _controller: RottenwoodArticleBundle:Api:getAllAuthors }
