parameters:
#    rottenwood_article.example.class: Rottenwood\ArticleBundle\Example

services:
#    rottenwood_article.example:
#        class: %rottenwood_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
